# Generated by Django 5.2.4 on 2025-07-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0005_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
