# Generated by Django 5.2.4 on 2025-07-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0006_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
