# Generated by Django 5.2.4 on 2025-08-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0010_remove_message_room_name_chatroom_message_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
