# Generated by Django 5.2.4 on 2025-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('posts', models.ManyToManyField(to='dothatlac.post')),
            ],
        ),
    ]
