# Generated by Django 5.2.4 on 2025-08-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0015_post_district_post_province_post_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='processing', max_length=50),
        ),
    ]
