# Generated by Django 5.2.4 on 2025-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0017_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_vector',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
