# Generated by Django 5.2.4 on 2025-08-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0020_alter_tag_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_time']},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
