# Generated by Django 5.2.4 on 2025-08-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0021_alter_post_options_alter_postimage_image_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
