# Generated by Django 5.2.4 on 2025-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0023_fcmtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
