# Generated by Django 5.2.4 on 2025-09-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0024_remove_user_phone_post_phone_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmtoken',
            old_name='updated_at',
            new_name='last_used',
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'token')},
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='device_type',
            field=models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fcmtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='fcmtoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fcmtoken',
            name='is_active',
        ),
    ]
