# Generated by Django 5.2.4 on 2025-09-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0025_rename_updated_at_fcmtoken_last_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='device_type',
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
