# Generated by Django 5.2.4 on 2025-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0027_comment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
