# Generated by Django 5.2.4 on 2025-09-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dothatlac', '0028_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
